import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";

export function CardOverlayEditor({
  imageUrl,
  lang,
}: {
  imageUrl: string;
  lang: "ru" | "en";
  initial?: unknown;
}) {
  const [busy, setBusy] = useState(false);
  const l = lang === "ru";

  const download = async () => {
    setBusy(true);
    try {
      const resp = await fetch(imageUrl);
      const blob = await resp.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `kartochka-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="grid gap-6 md:grid-cols-[1fr_320px]">
      <div className="mx-auto w-full max-w-md">
        <div className="relative aspect-[3/4] overflow-hidden rounded-xl border border-border/60 bg-muted">
          <img
            src={imageUrl}
            alt=""
            className="absolute inset-0 h-full w-full object-cover"
          />
        </div>
      </div>

      <div className="space-y-4">
        <p className="text-sm text-muted-foreground">
          {l
            ? "Карточка сгенерирована целиком моделью — заголовок и подзаголовок уже на изображении."
            : "The card is fully generated by the model — title and subtitle are already on the image."}
        </p>
        <Button
          onClick={download}
          disabled={busy}
          className="w-full bg-gradient-brand text-white hover:opacity-90"
        >
          {busy ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <Download className="mr-2 h-4 w-4" />
          )}
          {l ? "Скачать PNG" : "Download PNG"}
        </Button>
      </div>
    </div>
  );
}
